trigger:
- none

pool:
  vmImage: 'Ubuntu 20.04'
steps:
- ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
  - publish: '$(System.DefaultWorkingDirectory)'
    artifact: chromastg

- ${{ if eq(variables['Build.SourceBranchName'], 'test') }}:
  - publish: '$(System.DefaultWorkingDirectory)'
    artifact: chromatest

- ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
  - publish: '$(System.DefaultWorkingDirectory)'
    artifact: chromaprd 
